name: Run JSON to CSV Conversion

# Run this workflow when code is pushed to the main branch
on:
  push:
    branches:
      - main

jobs:
  json_csv_conversion:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Install google-cloud-storage if not in requirements.txt
        pip install google-cloud-storage

    # Step 4: Set up environment variables from GitHub Secrets
    - name: Set environment variables
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      # Write Google Cloud credentials to a file (required by google-cloud-storage)
      run: |
        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > ${{ github.workspace }}/google_credentials.json
        export GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/google_credentials.json

    # Step 5: Run the Python script
    - name: Run json_csv_gaia.py
      run: python3 data_handle/json_csv_gaia.py
